### ISSUE TITLE
Discord Webhooks Don't Work

### ISSUE THREAD

**Issue by ethaniccc** [Olybear9/Mavoric#15]
When I put my discord webhook in the config.yml, it didn't send anything. Yes, I know how to set up webhooks. Can you fix this issue? Thanks in advance.

**Comment by Olybear9** [comment]
This is a known issue and i will work on a fix now since it's been reported multiple times.

**Comment by Olybear9** [comment]
Hello @ethaniccc, I have attempted to fix this issue here: https://github.com/Olybear9/Mavoric/releases/tag/v1.0.3-alpha, please note that I have not tested these changes.
