### ISSUE TITLE
[BUG] Falling = Speed Hack

### ISSUE THREAD

**Issue by ethaniccc** [Olybear9/Mavoric#16]
Sorry for all the issues (lol), but I noticed this when I went on my KitPvP map. 

When you are falling, (from let's say 100 blocks high), the Anti-Cheat will flag it as speeding.
I don't really know how to explain it further

**Comment by Olybear9** [comment]
This should be fixed, can you give some more details on this?

**Comment by ethaniccc** [comment]
So basically, I have a kitpvp map where you fall around 100 to 150 blocks until you hit ground. When I'm falling, the Anti-cheat will say that I was detected moving too fast (by around 4 - 5 blocks) and restrict my falling movement. If you do it enough, the Anti-cheat will kick you.

**Comment by Olybear9** [comment]
You can disable kicks in the config by setting Autoban enabled to false.
```yml
Autoban:
  # Should autobans be enabled? (IF THIS IS ENABLED, BANWAVES ARE OVERRIDDEN REGARDLESS IF BANWAVES ARE ENABLED!)
  enabled: yes```

**Comment by Olybear9** [comment]
Speed is a terrible check right now, and I do look into different implementation for it on future versions

**Comment by Olybear9** [comment]
Closed in: https://github.com/Olybear9/Mavoric/commit/adf2ab19d8fa34a4bf83251a11c3582bf27255a5 @ethaniccc
