### ISSUE TITLE
[BUG] Report Error Code

### ISSUE THREAD

**Issue by brokiem** [Olybear9/Mavoric#37]
[Server thread/CRITICAL]: Error: "Class 'Bavfalcon9\Mavoric\Core\Detections\
JetPack' not found" (EXCEPTION) in "plugins/Mavoric_v1.0.4.phar/src/Bavfalcon9/Mavoric/

**Comment by brokiem** [comment]
at line 185

**Comment by Olybear9** [comment]
Thanks for reporting will recompile in a little bit.

**Comment by Olybear9** [comment]
Issue resolved. Here is the updated phar: [Mavoric_v1.0.4](https://github.com/Olybear9/Mavoric/releases/download/v1.0.4/Mavoric_v1.0.4.phar)
