### ISSUE TITLE
[BUG] Mavoric Not working properly?

### ISSUE THREAD

**Issue by PsychoPE** [Olybear9/Mavoric#43]
## Description
Mavoric not working

**To Reproduce**
1. Install Mavoric
2. Start server

**Expected behavior**
Doing something to moderate my friend.

**Actual Behavior**
Idk if it just doesnt work or if im missing a dependency plugin, but nothing happens im using the default config and my friend has just been using speed auto clicker reach and kill aura on me for the last 30 minutes

**What device are you using?**
- Windows 10

**Additional context**

**Comment by Olybear9** [comment]
Could you give more information on what version of mavoric you're using?

**Comment by Olybear9** [comment]
@PsychoPE To debug this I'll need some information from you:
Version of Mavoric:
Console Logs:
Any additional context

**Comment by PsychoPE** [comment]
latest dev build on poggit its #44 i think

**Comment by Olybear9** [comment]
Dev builds were intentionally made to be hard to use. Please use: https://github.com/Olybear9/Mavoric/releases/download/v1.0.4/Mavoric_v1.0.4.phar

**Comment by PsychoPE** [comment]
ok ill try it

**Comment by PsychoPE** [comment]
ok it works thanks
