### ISSUE TITLE
[BUG] Fly Detect

### ISSUE THREAD

**Issue by ethaniccc** [Olybear9/Mavoric#51]
## Description
The anti-cheat will mark you as flying with the alert: [MAVORIC] (Player Name) failed test for Flight: Illegal movement, jumped on air.

**Additional context**
It occurs when I use my KitPvP plugin: when the player interacts with a certain item that set's their motion with `$player->setMotion();`

**Comment by Olybear9** [comment]
Known issue, this cheat is in development, for now just disable it in the config.
