### ISSUE TITLE
[BUG] MREPORT ISE

### ISSUE THREAD

**Issue by cchar101** [Olybear9/Mavoric#54]
I might just be stupid, but when trying to do **/mreport (name) reach(any)** it kicks me and gives an ISE.

Using Latest (Mavoric v1.0.5 from Poggit)

`[10:39:12] [Server thread/CRITICAL]: Error: "Call to undefined method Bavfalcon9\Mavoric\Core\Utils\CheatIdentifiers::getCheatFromString()" (EXCEPTION) in "plugins/Mavoric.phar/src/Bavfalcon9/Mavoric/Core/Miscellaneous/CheatTranslation" at line 38`

If it's something simple, I apologise.

Thanks for your help.

**Comment by Olybear9** [comment]
Known issue this will be fixed in v1.0.6

**Comment by cchar101** [comment]
Okay, ty
