### ISSUE TITLE
[BUG] Reach crashes on latest release

### ISSUE THREAD

**Issue by ethaniccc** [Olybear9/Mavoric#55]
## Description
When Player is detected for using REACH, the plugin returns and error and crashes the player (not the server).

**Additional context**
Reach is detected sometimes when using a knock back stick (1) and high CPS.

**Comment by Olybear9** [comment]
Known issue, this was patched in v1.0.6 which has no known release date

**Comment by Olybear9** [comment]
Fixed in: 8d29ecdb997ba6f54ab7a5077fca154944209fc3

**Comment by ethaniccc** [comment]
Something to note (I guess) is that I had to make assets/context.txt manually until the plugin worked.

**Comment by Olybear9** [comment]
That should only be an issue on dev versions. I'll look into that, not sure why that remained in public version

**Comment by ethaniccc** [comment]
the problem was in the dev version
sorry for not clarifying that :p
